# ansible -m copy -a "dest=hello content=world" localhost --check --diff

- name: install nginx
  hosts: pi3
  tags: nginx
  check_mode: true
  diff: true
  tasks:
    - ansible.builtin.apt:
        name: nginx
      
- name: copy module test
  hosts: localhost
  tasks:
    - copy:
        dest: hello
        content: world
    - command: date